### ISSUE TITLE
Add nuxt 3 support

### ISSUE THREAD

**Issue by FaryarKankash** [alireza-ab/vue3-persian-datepicker#12]
Add nuxt 3 support 
in nuxt 3 your component have error and if i use <ClientOnly> wrapper it dosent show up

**Comment by alireza-ab** [comment]
Hi @FaryarKankash. I'm sorry about the late.
Please see this: https://github.com/alireza-ab/vue3-persian-datepicker/issues/8#issuecomment-1859053773
