### ISSUE TITLE
typescript definition issue 

### ISSUE THREAD

**Issue by abbasQorbani** [alireza-ab/vue3-persian-datepicker#13]
I know this package is ts supported, but I can't figure out why this error will happen
![image](https://github.com/alireza-ab/vue3-persian-datepicker/assets/50130369/e4d1b6cf-ffa7-4501-b402-a57e11c7b051)

**Comment by alireza-ab** [comment]
Hi @abbasQorbani 
I'm sorry about the late.
Thank you for reporting this. This is fixed now.
