### ISSUE TITLE
display problem on modals if picker not fit on modal size

### ISSUE THREAD

**Issue by jafarkzemit** [alireza-ab/vue3-persian-datepicker#14]
I use date-picker on modal, some times depend on it's position, part of picker may be hide.

![image](https://github.com/alireza-ab/vue3-persian-datepicker/assets/9779812/8369dba3-b30b-428f-be8a-60a66d8cd1fe)

**Comment by jafarkzemit** [comment]
if it possible to customize the size of picker, it would be perfect.

**Comment by alireza-ab** [comment]
Hi @jafarkzemit 
I think the problem is about the styles. Does the modal have an `overflow` property?
I don't think that customizing the size of the picker would fix the problem but by changing the picker styles you could do that.
