### ISSUE TITLE
When building my app, I receive the following warning: the modules is strongly discouraged as it poses security risks and may cause issues with minification

### ISSUE THREAD

**Issue by AmirHo3sein** [alireza-ab/vue3-persian-datepicker#16]
Hi
When building my app, I receive the following warning:
 node_modules/@alireza-ab/vue3-persian-datepicker/dist/index-es.js (8:18542): The use of eval in node_modules/@alireza-ab/vue3-persian-datepicker/dist/index-es.js is strongly discouraged as it poses security risks and may cause issues with minification
 
Vue version : ^3.4.21
vite version: "^5.1.6",

**Comment by alireza-ab** [comment]
Hi @AmirHo3sein 
The warning is from `persian-date` package. In the package,  `eval` function is used. This must be fixed in that package.
Thanks for reporting.
