### ISSUE TITLE
how to use in Nuxt 3?

### ISSUE THREAD

**Issue by ahadihadi** [alireza-ab/vue3-persian-datepicker#8]
how to use in Nuxt 3 with ssr?

**Comment by alireza-ab** [comment]
Hi @ahadihadi. I'm sorry about the late.
after installing the component, add to the `nuxt.config.ts`:
```js
export default defineNuxtConfig({
  modules: ["@alireza-ab/vue3-persian-datepicker/nuxt"]
});
```
after that, you can use `DatePicker` component in your files without the need to import it:

```vue
<DatePicker />
```
